### ISSUE TITLE
Loading swup plugins into Astro config

### ISSUE THREAD

**Issue by dshook** [swup/astro#26] opened 2024-09-17 01:04 UTC
### What did you expect? 🧐

a11y-plugin to work installing it in astro.config.mjs

### What actually happened? 😵‍💫

Got an error running dev command:

```
8:53:59 PM [vite] Error when evaluating SSR module /Users/dillonshook/site-astro/astro.config.mjs:
|- ReferenceError: document is not defined
    at i.getRegion (file:///Users/dillonshook/site-astro/node_modules/.pnpm/@swup+a11y-plugin@5.0.0_swup@4.7.0/node_modules/@swup/a11y-plugin/dist/index.modern.js:1:711)
    at new i (file:///Users/dillonshook/site-astro/node_modules/.pnpm/@swup+a11y-plugin@5.0.0_swup@4.7.0/node_modules/@swup/a11y-plugin/dist/index.modern.js:1:664)
    at new r (file:///Users/dillonshook/site-astro/node_modules/.pnpm/@swup+a11y-plugin@5.0.0_swup@4.7.0/node_modules/@swup/a11y-plugin/dist/index.modern.js:1:1897)
    at /Users/dillonshook/site-astro/astro.config.mjs:41:17
    at async instantiateModule (file:///Users/dillonshook/site-astro/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.1_lightningcss@1.26.0_sass@1.77.8_stylus@0.63.0_terser@5.31.6/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52870:5)
[astro] Unable to load your Astro config
document is not defined
  Hint:
    Browser APIs are not available on the server.
    
    If the code is in a framework component, try to access these objects after rendering using lifecycle methods or use a `client:only` directive to make the component exclusively run on the client.
    
    See https://docs.astro.build/en/guides/troubleshooting/#document-or-window-is-not-defined for more information.
    
  Stack trace:
    at i.getRegion (file:///Users/dillonshook/site-astro/node_modules/.pnpm/@swup+a11y-plugin@5.0.0_swup@4.7.0/node_modules/@swup/a11y-plugin/dist/index.modern.js:1:711)
    at new r (file:///Users/dillonshook/site-astro/node_modules/.pnpm/@swup+a11y-plugin@5.0.0_swup@4.7.0/node_modules/@swup/a11y-plugin/dist/index.modern.js:1:1897)
    at async instantiateModule (file:///Users/dillonshook/site-astro/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.1_lightningcss@1.26.0_sass@1.77.8_stylus@0.63.0_terser@5.31.6/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52870:5)
 ELIFECYCLE  Command failed with exit code 1.
```

This was after I added the import
`import SwupA11yPlugin from '@swup/a11y-plugin';`

And the plugin:

```

export default defineConfig({
  ...
  integrations: [
    ...
    swup({
      plugins: [new SwupA11yPlugin()],
      theme: false,
      animationClass: 'transition-swup-',   // see https://swup.js.org/options/#animationselector
                                            // the default value `transition-` cause transition delay
                                            // when the Tailwind class `transition-all` is used
      containers: ['main'],
      smoothScrolling: true,
      cache: true,
      preload: true,
      accessibility: true,
      updateHead: true,
      updateBodyClass: false,
      globalInstance: true,
    }),
```

### Swup and plugin versions 📝

    "@swup/a11y-plugin": "^5.0.0",
    "@swup/astro": "^1.4.1",

### URL to minimal reproduction 🔗

-

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment] 2024-09-17 06:27
The astro integration doesn't directly take in swup plugins. It's a wrapper around swup and the most important plugins, of which the a11y plugin is already enabled. So you shouldn't have to include that manually here. If the goal is to tweak the settings of the a11y plugin, you'll need to switch to a [manual swup setup](https://github.com/swup/astro/?tab=readme-ov-file#control-over-the-initialization).

I'll close this one as it's not a bug, but feel free to get back if the above doesn't answer your question.

**Closed by daun** 2024-09-17 06:27 UTC
